export const individualChats = [
    {
        id: '1',
        name: 'João Victor',
        lastMessage: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        lastMessageTime: '12:00',
        unreadMessages: 1,
        isGroup: false,
    },
    {
        id: '2',
        name: 'João Victor',
        lastMessage: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        lastMessageTime: '12:00',
        unreadMessages: 1,
        isGroup: false,
    },
    {
        id: '3',
        name: 'João Victor',
        lastMessage: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        lastMessageTime: '12:00',
        unreadMessages: 1,
        isGroup: false,
    },
    {
        id: '4',
        name: 'João Victor',
        lastMessage: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        lastMessageTime: '12:00',
        unreadMessages: 1,
        isGroup: false,
    },
    {
        id: '5',
        name: 'João Victor',
        lastMessage: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        lastMessageTime: '12:00',
        unreadMessages: 1,
        isGroup: false,
    },
    {
        id: '6',
        name: 'João Victor',
        lastMessage: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        lastMessageTime: '12:00',
        unreadMessages: 1,
        isGroup: false,
    },
];

export const groupChats = [
    {
        id: '1',
        name: 'Família Silva',
        lastMessage: 'Oi pessoal, como estão?',
        lastMessageTime: '09:30',
        unreadMessages: 3,
        isGroup: true,
        nameFromPersonLastMessage: 'Ana Silva',
    },
    {
        id: '2',
        name: 'Amigos da Faculdade',
        lastMessage: 'Vamos marcar um encontro este fim de semana?',
        lastMessageTime: '18:15',
        unreadMessages: 2,
        isGroup: true,
        nameFromPersonLastMessage: 'Carlos Oliveira',
    },
    {
        id: '3',
        name: 'Projeto de Trabalho',
        lastMessage: 'Precisamos finalizar a apresentação até sexta-feira.',
        lastMessageTime: '14:45',
        unreadMessages: 1,
        isGroup: true,
        nameFromPersonLastMessage: 'Juliana Santos',
    },
    {
        id: '4',
        name: 'Grupo de Jogos Online',
        lastMessage: 'Quem está pronto para uma partida hoje à noite?',
        lastMessageTime: '22:00',
        unreadMessages: 4,
        isGroup: true,
        nameFromPersonLastMessage: 'Gabriel Pereira',
    },
    {
        id: '5',
        name: 'Comunidade Fitness',
        lastMessage: 'Novo desafio de 30 dias começando amanhã, quem topa?',
        lastMessageTime: '20:30',
        unreadMessages: 0,
        isGroup: true,
        nameFromPersonLastMessage: 'Larissa Fernandes',
    },
    {
        id: '6',
        name: 'Clube do Livro',
        lastMessage: 'Vamos escolher o próximo livro para leitura em grupo?',
        lastMessageTime: '16:20',
        unreadMessages: 1,
        isGroup: true,
        nameFromPersonLastMessage: 'Mariana Costa',
    },
    {
        id: '7',
        name: 'Equipe de Desenvolvimento',
        lastMessage: 'Reunião de sprint na sexta-feira às 10h.',
        lastMessageTime: '11:00',
        unreadMessages: 0,
        isGroup: true,
        nameFromPersonLastMessage: 'Lucas Oliveira',
    },
    {
        id: '8',
        name: 'Grupo de Viagem',
        lastMessage: 'Roteiro definido! Ansiosos para a viagem?',
        lastMessageTime: '08:45',
        unreadMessages: 2,
        isGroup: true,
        nameFromPersonLastMessage: 'Fernanda Santos',
    },
    {
        id: '9',
        name: 'Clube de Música',
        lastMessage: 'Playlist da semana: rock dos anos 80!',
        lastMessageTime: '13:10',
        unreadMessages: 0,
        isGroup: true,
        nameFromPersonLastMessage: 'Gustavo Lima',
    },
    {
        id: '10',
        name: 'Grupo de Estudos de Idiomas',
        lastMessage: 'Próxima aula: quinta-feira, 19h.',
        lastMessageTime: '17:50',
        unreadMessages: 1,
        isGroup: true,
        nameFromPersonLastMessage: 'Isabela Martins',
    },
    {
        id: '11',
        name: 'Time de Futebol',
        lastMessage: 'Treino adiado para quarta-feira, 18h.',
        lastMessageTime: '15:30',
        unreadMessages: 3,
        isGroup: true,
        nameFromPersonLastMessage: 'Ricardo Almeida',
    },
    {
        id: '12',
        name: 'Grupo de Tecnologia',
        lastMessage: 'Nova tecnologia de inteligência artificial em pauta.',
        lastMessageTime: '12:20',
        unreadMessages: 0,
        isGroup: true,
        nameFromPersonLastMessage: 'Felipe Oliveira',
    },
    {
        id: '13',
        name: 'Mães do Bairro',
        lastMessage: 'Passeio no parque neste sábado, quem vai?',
        lastMessageTime: '10:40',
        unreadMessages: 2,
        isGroup: true,
        nameFromPersonLastMessage: 'Patrícia Lima',
    },
    {
        id: '14',
        name: 'Clube de Fotografia',
        lastMessage: 'Desafio da semana: retratos em preto e branco.',
        lastMessageTime: '14:00',
        unreadMessages: 1,
        isGroup: true,
        nameFromPersonLastMessage: 'Marcos Oliveira',
    },
    {
        id: '15',
        name: 'Grupo de Caronas',
        lastMessage: 'Alguém precisa de carona para o trabalho amanhã?',
        lastMessageTime: '07:30',
        unreadMessages: 0,
        isGroup: true,
        nameFromPersonLastMessage: 'Camila Santos',
    },
    {
        id: '16',
        name: 'Clube de Culinária',
        lastMessage: 'Receita do dia: lasanha à bolonhesa!',
        lastMessageTime: '19:00',
        unreadMessages: 1,
        isGroup: true,
        nameFromPersonLastMessage: 'Rodrigo Alves',
    },
    {
        id: '17',
        name: 'Grupo de Voluntariado',
        lastMessage: 'Próximo evento de arrecadação: sábado, 14h.',
        lastMessageTime: '16:45',
        unreadMessages: 0,
        isGroup: true,
        nameFromPersonLastMessage: 'Eduarda Martins',
    },
    {
        id: '18',
        name: 'Clube de Dança',
        lastMessage: 'Aula de dança de salão hoje à noite!',
        lastMessageTime: '20:15',
        unreadMessages: 2,
        isGroup: true,
        nameFromPersonLastMessage: 'Antônio Silva',
    },
    {
        id: '19',
        name: 'Grupo de Finanças',
        lastMessage: 'Dicas de investimentos para o próximo mês.',
        lastMessageTime: '15:20',
        unreadMessages: 0,
        isGroup: true,
        nameFromPersonLastMessage: 'Mariana Oliveira',
    },
    {
        id: '20',
        name: 'Clube de Artes',
        lastMessage: 'Exposição de arte no museu no sábado, quem vai?',
        lastMessageTime: '11:30',
        unreadMessages: 1,
        isGroup: true,
        nameFromPersonLastMessage: 'Vinícius Lima',
    },
];
